#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
OHMYZSH_DIR=".oh-my-zsh/custom/themes/powerlevel10k"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"
git -C "${OHMYZSH_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${OHMYZSH_DIR}"

# rm -rf $HOME/.oh-my-zsh
rm -rf $HOME/.zshrc.pre-oh-my-zsh* 

which -s brew || yes '' | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
[[ -d "$HOME/.oh-my-zsh" ]] || bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

xargs -r brew install -v < <(comm -23 ${BASEDIR}/packages/homebrew <(brew list --formula -1)) || xargs -r brew install <${BASEDIR}/packages/homebrew
xargs -r brew install --cask -v < <(comm -23 ${BASEDIR}/packages/homebrew-cask <(brew list --cask -1))
GO111MODULE=on xargs go get -u -v <${BASEDIR}/packages/go
xargs -r cargo install <${BASEDIR}/packages/cargo

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

tmux new-session -d -s setup-tmux 'nvim +"TmuxlineSnapshot $HOME/.vim/plugged/tmuxline.vim/tmux.conf" +qa'
pyenv install --skip-existing 3.8.5
pyenv global 3.8.5
