#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
OHMYZSH_DIR=".oh-my-zsh/custom/themes/powerlevel10k"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"
git -C "${OHMYZSH_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${OHMYZSH_DIR}"

rm -rf $HOME/.oh-my-zsh
rm -rf $HOME/.zshrc.pre-oh-my-zsh* 

which -s brew || yes '' | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

xargs brew install <${BASEDIR}/packages/homebrew

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

curl -fLo "${HOME}/Library/fonts/MesloLGS NF Regular.ttf" --create-dirs https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
curl -fLo "${HOME}/Library/fonts/MesloLGS NF Bold.ttf" --create-dirs https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
curl -fLo "${HOME}/Library/fonts/MesloLGS NF Italic.ttf" --create-dirs https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
curl -fLo "${HOME}/Library/fonts/MesloLGS NF Bold Italic.ttf" --create-dirs https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf

curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
tmux new-session -s setup-tmux 'nvim -u "$HOME/.config/nvim/plugins.vim" +"PlugInstall --sync" +"UpdateRemotePlugins" +"Tmuxline airline" +"TmuxlineSnapshot $HOME/.vim/plugged/tmuxline.vim/tmux.conf" +qa'
pyenv install --skip-existing 3.9.0
pyenv global 3.9.0
